version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: kanban-postgres
    environment:
      POSTGRES_DB: kanban
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kanban-backend
    environment:
      DATABASE_URL: postgresql://admin:adminpassword@postgres:5432/kanban?schema=public
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: 'http://localhost:3000'
    container_name: kanban-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  postgres_data: